// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = 'https://wrvyxkflqmnknescnlwz.supabase.co'
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indydnl4a2ZscW1ua25lc2NubHd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NzI0NDEsImV4cCI6MjA2NjM0ODQ0MX0.o6cH6jnfE5DVIeaX_svUYe4VF1KTE9rEFpF1J2VVNT4'

export const supabase = createClient(supabaseUrl, supabaseKey)
